spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/QuiroHappy?createDatabaseIfNotExist=true
    username: root
    password: 1299

